scinage/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'cas.views.login', name='login'),
    url(r'^accounts/logout/$', 'cas.views.logout', name='logout'),


    url(r'^$', 'layers.views.frontpage', name="home"),
    url(r'^uploadimage/$', 'layers.views.ajaximage', name="upload_image"),
    # Layer Editing
    url(r'^extracontrols/$', 'layers.views.controlsExtra', name="extra_controls"),

    url(r'^layers/search/', include('haystack.urls')),
    url(r'^layers/$', 'layers.views.manageLayers', name="layers"),
    url(r'^layers/list/(?P<mode>\w+)/$', 'layers.views.listLayers', name="list_layers"),
    url(r'^layers/new/$', 'layers.views.editLayer', name="new_layer"),
    url(r'^layers/clone/(?P<layer_id>\d+)/$', 'layers.views.cloneLayer', name="clone_layer"),
    url(r'^layers/edit/(?P<layer_id>\d+)/$', 'layers.views.editLayer', name="edit_layer"),
    url(r'^layers/delete/(?P<layer_id>\d+)/$', 'layers.views.editLayer', name="delete_layer"),
    url(r'^layers/view/(?P<layer_id>\d+)/$', 'layers.views.editLayer', name="view_layer"),
    url(r'^layers/editorinput/(?P<id>\d+)/$', 'layers.views.loadInput'),
    url(r'^layers/favlayer/$', 'layers.views.toggleLayerFav', name='favlayer'),

    # Slide Editing
    url(r'^slides/$', 'layers.views.manageSlides', name="slides"),
    url(r'^slides/list/(?P<mode>\w+)/$', 'layers.views.listSlides', name="list_slides"),
    url(r'^slides/new/$', 'layers.views.editSlide', name="new_slide"),
    url(r'^slides/clone/(?P<slide_id>\d+)/$', 'layers.views.cloneSlide', name="clone_slide"),
    url(r'^slides/edit/(?P<slide_id>\d+)/$', 'layers.views.editSlide', name="edit_slide"),
    url(r'^slides/delete/(?P<slide_id>\d+)/$', 'layers.views.editSlide', name="delete_slide"),
    url(r'^slides/layersettings/(?P<version_id>\d+)/$', 'layers.views.layerSettings'),
    url(r'^slides/layerjson/new/(?P<version_id>\d+)/$', 'layers.views.newLayerJson'),
    url(r'^slides/layerpreview/$', 'layers.views.previewLayer'),

    # Slide Viewing
    url(r'^slides/view/(?P<slide_id>\d+)/$', 'layers.views.viewSlide', name="view_slide"),


    # Slideshow Viewing
    url(r'^slideshows/$', 'layers.views.manageSlideshows', name="slideshows"),
    url(r'^slideshows/list/(?P<mode>\w+)/$', 'layers.views.listSlideshows', name="list_slideshows"),
    url(r'^slideshows/new/$', 'layers.views.editSlideshow', name="new_slideshow"),
    url(r'^slideshows/clone/(?P<slideshow_id>\d+)/$', 'layers.views.cloneSlideshow', name="clone_slideshow"),

    url(r'^slideshows/edit/(?P<slideshow_id>\d+)/$', 'layers.views.editSlideshow', name="edit_slideshow"),
    url(r'^slideshows/delete/(?P<slideshow_id>\d+)/$', 'layers.views.editSlideshow', name="delete_slideshow"),
    url(r'^slideshows/nextslide/(?P<slideshow_id>\d+)/(?P<current_index>\d+)/$', 'layers.views.nextSlide'),
    url(r'^slideshows/view/(?P<slideshow_id>\d+)/$', 'layers.views.viewSlideshow', name="view_slideshow"),

    # Screen Viewing
    url(r'^screens/$', 'layers.views.manageScreens', name="screens"),
    url(r'^screens/list/$', 'layers.views.listScreens', name="list_screens"),
    url(r'^screens/new/$', 'layers.views.editScreen', name="new_screen"),
    url(r'^screens/edit/(?P<screen_id>\d+)/$', 'layers.views.editScreen', name="edit_screen"),
    url(r'^screens/delete/(?P<screen_id>\d+)/$', 'layers.views.editScreen', name="delete_screen"),
    url(r'^screens/view/(?P<slug>[-\w\d]+)/$', 'layers.views.viewScreen', name="view_screen"),
    url(r'^screens/ping/(?P<slug>[-\w\d]+)/$', 'layers.views.pingScreen', name="ping_screen"),


    # Station Stuff
    url(r'^stations/$', 'layers.views.manageStations', name="stations"),

    # Group stuff
    url(r'^groups/$', 'layers.views.manageGroups', name="groups"),
    url(r'^groups/list/(?P<mode>\w+)/$', 'layers.views.listGroups', name="list_groups"),
    url(r'^groups/new/$', 'layers.views.editGroup', name="new_group"),
    url(r'^groups/edit/(?P<group_id>\d+)/$', 'layers.views.editGroup', name="edit_group"),
     url(r'^groups/view/(?P<group_id>\d+)/$', 'layers.views.viewGroup', name="view_group"),
    url(r'^groups/delete/(?P<group_id>\d+)/$', 'layers.views.editGroup', name="delete_group"),

    # Sharing
    url(r'^share/(?P<item>\w+)/(?P<pk>\d+)/$', 'layers.views.shareSettings', name="sharesettings"),
    url(r'^transfer/(?P<item>\w+)/(?P<pk>\d+)/$', 'layers.views.transferOwnership', name="transfer"),

]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static('/media/', document_root=settings.MEDIA_ROOT)

layers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator, ValidationError

from django.db.models.deletion import Collector
from django.db.models.fields.related import ForeignKey

from django.utils.text import slugify

from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFit, ResizeToFill

from taggit.managers import TaggableManager
from haystack import signals

"""
When a user creates a new layer, it will create a version to go with it.
Anytime a user wants to change what their layer looks like, it will create a new
version for the revision, and (if it is not shared) offer to delete older versions.

A version is simply a list of input types and the jinja2(?) html code to render the object

Input types will each contain html / css / js to add an extra field for users to fill in.
We'll have colorpickers and shit.
"""
variable = RegexValidator(r'^[a-zA-Z]{1}[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed. Must start with a letter.')


class UploadedImage(models.Model):
    owner = models.ForeignKey(User)
    creation_date = models.DateTimeField(auto_now_add=True)
    image = ProcessedImageField(upload_to='uploaded_images',
                                processors=[ResizeToFit(1280, 720, False)],
                                format='PNG',
                                options={'quality': 80})
    thumbnail = ImageSpecField(source='image',
                               processors=[ResizeToFit(100, 100)],
                               format='JPEG',
                               options={'quality': 60})


class Layer(models.Model):
    owner = models.ForeignKey(User)
    creation_date = models.DateTimeField(auto_now_add=True)
    shared = models.BooleanField(default=False)
    official = models.BooleanField(default=False)
    title = models.CharField(max_length=255)
    short = models.CharField(max_length=12)
    description = models.TextField()
    tags = TaggableManager()

    # tags
    icon = ProcessedImageField(upload_to='icons',
                               processors=[ResizeToFit(72, 72)],
                               format='PNG',
                               options={'quality': 80},
                               blank=True, null=True)

    def bleeding_edge(self):
        pass

    def latest(self):
        try:
            return self.version_set.filter(publish=True).order_by('-creation_date')[0:1].get()
        except:
            return self.version_set.order_by('-creation_date')[0:1].get()

    def uses(self):
        return SlideLayer.objects.filter(version__layer=self).count()

    def favs(self):
        return self.favoritelayer_set.all().count()

    def clone(self, user):
        newlayer = Layer.objects.get(id=self.id)
        newlayer.id = None
        newlayer.shared = False
        newlayer.official = False
        newlayer.title = "CLONE OF %s" % self.title
        newlayer.owner = user

        newlayer.save()

        # And make the version...
        oldversion = self.latest()
        newversion = self.latest()

        newversion.id = None
        newversion.publish = False
        newversion.changes = ''
        newversion.layer = newlayer
        newversion.save()
        for control in oldversion.control_set.all():
            newcontrol = Control(version=newversion,
                                 title=control.title,
                                 variable_name=control.variable_name,
                                 verbose=control.verbose,
                                 input_type=control.input_type,
                                 default=control.default)
            newcontrol.save()
        return newlayer


class FavoriteLayer(models.Model):
    user = models.ForeignKey(User)
    layer = models.ForeignKey(Layer)


class Version(models.Model):
    layer = models.ForeignKey(Layer)
    content = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)
    changes = models.TextField(blank=True)
    publish = models.BooleanField(default=False)
    # every edit after a publish will be a new version!

    last_edit = models.ForeignKey(User, blank=True, null=True, related_name='version_last_edit')

    def save(self, *args, **kwargs):
        super(Version, self).save(*args, **kwargs)
        if self.publish is True:
            # We're going to do this by hand because stackoverflow only has answers for ancient versions of django
            # and I spent too bloody long trying to write a general duplicator and got only nonsense error messages
            # Duplicate the object to make a new HEAD version.
            new = Version(layer=self.layer, content=self.content, publish=False, last_edit=self.last_edit)
            new.save()
            # Get all the controls too
            for control in self.control_set.all():
                newcontrol = Control(version=new,
                                     title=control.title,
                                     variable_name=control.variable_name,
                                     verbose=control.verbose,
                                     input_type=control.input_type,
                                     default=control.default)
                newcontrol.save()


class InputType(models.Model):
    title = models.CharField(max_length=255)
    html = models.TextField()
    validator = models.CharField(max_length=255)
    validator_error = models.CharField(max_length=255)

    def __unicode__(self):
        return self.title


class Control(models.Model):
    version = models.ForeignKey(Version)
    title = models.CharField(max_length=255)
    variable_name = models.CharField(max_length=18)
    verbose = models.TextField(blank=True)
    input_type = models.ForeignKey(InputType)
    default = models.CharField(max_length=255)


class Slide(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    data = models.TextField(blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    last_edit = models.ForeignKey(User, null=True, related_name='slide_edit_user', blank=True)

    # Advanced Settings
    aspect_ratio = models.CharField(max_length=8, default="16x9",
                                    validators=[RegexValidator(
                                    regex='^(\d+x\d+)$',
                                    message='Must be in the form WidthxHeight',)])

    def clone(self, user):
        # Clone the original...
        newslide = Slide.objects.get(pk=self.id)
        newslide.pk = None
        newslide.owner = user
        newslide.title = 'CLONE OF %s' % self.title
        newslide.save()

        # And get all the slidelayers
        for sl in self.slidelayer_set.all():
            sl.pk = None
            sl.slide = newslide
            sl.save()
        return newslide


class SlideLayer(models.Model):
    slide = models.ForeignKey(Slide)
    x = models.FloatField(default=40)
    y = models.FloatField(default=40)
    width = models.FloatField(default=20)
    height = models.FloatField(default=20)
    title = models.CharField(max_length=100)
    index = models.IntegerField()
    version = models.ForeignKey(Version)
    data = models.TextField(blank=True)

    def control(self):
        return self.version.control


class Slideshow(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    last_edit = models.ForeignKey(User, null=True, related_name='slideshow_last_edit', blank=True)

    def clone(self, user):
        # Clone the original...
        newslideshow = Slideshow.objects.get(pk=self.id)
        newslideshow.pk = None
        newslideshow.owner = user
        newslideshow.title = 'CLONE OF %s' % self.title
        newslideshow.save()

        # And get all the slideshowslides
        for sl in self.slideshowslide_set.all():
            sl.pk = None
            sl.slideshow = newslideshow
            sl.save()
        return newslideshow


class SlideshowSlide(models.Model):
    slideshow = models.ForeignKey(Slideshow)
    slide = models.ForeignKey(Slide)
    length = models.IntegerField(default=30)
    order = models.IntegerField()


class Channel(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    last_edit = models.ForeignKey(User, null=True, related_name='channel_last_edit', blank=True)


class ChannelItem(models.Model):
    channel = models.ForeignKey(Channel)

    # Is it a slide or a slideshow? Form requires one or the other to be true
    slide = models.ForeignKey(Slide, blank=True, null=True)
    slideshow = models.ForeignKey(Slideshow, blank=True, null=True)

    priority = models.IntegerField(default=1)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    repeat = models.CharField(max_length=200)


class Screen(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255, unique=True, help_text="If title changes after initial configuration, URL will change.")
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=255)

    link = models.CharField(max_length=255)
    ip = models.GenericIPAddressField(blank=True, null=True)
    last_connect = models.DateTimeField(blank=True, null=True)

    def save(self, *args, **kwargs):

templates/screens/editscreen.html
{% extends 'UI/skin.html' %}
{% load breadcrumbs %}

{% block breadcrumbs %}
{% breadcrumb_url 'Screen' 'screens' %}
	{% if screen != None %}
	{% with "Edit: "|add:screen.title as current %}
		{% breadcrumb current %}
	{% endwith %}
	{% else %}
    {% breadcrumb 'New Screen' %}
    {% endif %}
{% endblock %}

{% block style %}

	<style>
		.addbuttoncontainer{
			display: block;
		}
		#currentItem .addbuttoncontainer{
			display: none;
		}
		#currentItem{
			padding: 8px;
			border-color: grey;
			border: 3px dashed;
			min-height: 20px;
			width: 100%;
			margin: 8px;
		}
	</style>

{% endblock %}

{% block body %}
	<div class="col-lg-6 col-xs-12">
		<form id="screen_form" method="POST" action="" >
		{% load crispy_forms_tags %}
		{% load slide_tags %}

		{% crispy form %}

		<div id="currentItem" class='row'>
			{% if item == None %}
				Select an item to point this screen to below...
			{% else %}
				{% if itemtype == 'slideshows' %}
					{% slideshow_item item %}
				{% elif itemtype == 'slides' %}
					{% slide_item item %}
				{% endif %}
			{% endif %}
		</div>
		<button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
		  Choose what to show on this screen
		</button>
		<br><br>
		<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog modal-lg" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">Select object to link to</h4>
	      </div>
	      <div class="modal-body">
		      <ul id="AllTabs" class="nav nav-pills" role="tablist" style="">
		      		  <li role="presentation" class="active"><a href="#all_slideshows" aria-controls="all_slideshows" role="tab" data-toggle="tab">Slideshows</a></li>
		      		  <li role="presentation"><a href="#all_slides" aria-controls="all_slides" role="tab" data-toggle="tab">Slides</a></li>
		      </ul>
		      <div id="all_panes" class="tab-content" style="">
		      	<div role="tabpanel" class="tab-pane active" id="all_slideshows">
		      	</div>
		      	<div role="tabpanel" class="tab-pane" id="all_slides">
		      	</div>
		      </div>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	      </div>
	    </div>
	  </div>
	</div>
{% endblock %}

{% block script %}
	<script>
	$('#all_slideshows').load('{% url "list_slideshows" mode="edit" %}');
	$('#all_slides').load('{% url "list_slides" mode="edit" %}');
	$('#all_panes').on('click', '.addslidebutton', function(){
		var item = $(this).closest('.slideItem>.itemContainer').clone();
		$(item).find('.addbuttoncontainer').remove();
		$('#currentItem').html(item);
		$('#id_link').val('/slides/view/'+$(this).closest('.slideItem').data('id')+'/');
		$('#myModal').modal('hide')

	})
	$('#all_panes').on('click', '.addslideshowbutton', function(){
		var item = $(this).closest('.slideshowItem>.itemContainer').clone();
		$(item).find('.addbuttoncontainer').remove();
		$('#currentItem').html(item);
		$('#id_link').val('/slideshows/view/'+$(this).closest('.slideshowItem').data('id')+'/');
		$('#myModal').modal('hide')
	})


	</script>
{% endblock %}

templates/screens/screen_item.html
<div data-id="{{screen.id}}" data-title="{{screen.title}}" class="screenItem {% if mode == "use" or mode == "edit"%}col-xs-6 col-sm-4 col-md-3{% else %}col-xs-12{% endif %}">
	<div class="itemContainer itemContainerScreen row">
	<div class="col-xs-12">
		<span class=""><i class="fa fa-th-list"></i></span>
		<span class="pull-right">
		
		</span>
	</div>
	<div class="col-xs-8">
	<div class="col-xs-12{% if mode == "manage"%}{% else %}text-center{% endif %}">
		<h4 style="margin:0; margin-top:5px"><b>{{screen.title}}</b> 
		<small>(by: {% if screen.owner = user %}Me{% else %} {{screen.owner.username}}{% endif %})
		<br>
		Last Seen: {{screen.last_connect|date:"Y/m/d H:m"}}
		<br>
		IP Address: {{screen.ip}}
		<br>
		URL: https://scinage.uwaterloo.ca/screens/view/{{screen.slug}}/
		</small>

		</h4>

	</div>
		<div class="col-xs-12 itemDescription" style="min-height:100%; margin-top:10px;">
			<p><small></small></p>
			<p>{{screen.description}}</p>
		</div>
	</div>
		<div class="col-xs-4">
			<div class="btn-group-vertical btn-block" role="group" aria-label="...">
				{% if perms.share == True %}<button class="sharebutton btn btn-primary btn-sm" data-itempk="{{screen.id}}">Share</button>{% endif %}
				{% if perms.edit == True %}<a href="{% url 'edit_screen' screen.id %}" class="btn btn-primary btn-sm">Edit</a>{% endif %}
				{% if user == screen.owner %}
				<button class="transferbutton btn btn-primary btn-sm" data-itempk="{{screen.id}}">Transfer</button>
				{% endif %}
				{% if perms.delete == True %}<a href="{% url 'delete_screen' screen.id %}" class="btn btn-primary btn-sm">Delete</a>{% endif %} 
				<a href="{% url 'view_screen' screen.slug %}" class="btn btn-primary btn-sm">View</a>
			</div>
		</div>
	</div>
</div>

templates/screens/screen_list.html
<ul id="screentabs" class="nav nav-tabs" role="tablist" style="margin-top:10px;">
		  <li role="presentation" class="active"><a href="#my_screens" aria-controls="my_screens" role="tab" data-toggle="tab">My Screens</a></li>
		  <li role="presentation"><a href="#group_screens" aria-controls="group_screens" role="tab" data-toggle="tab">Screens in Groups</a></li>
</ul>
<div id="screenpanes" class="tab-content" style="">
	<div class="input-group" style="padding:20px;">
	  <input type="text" id="my_screens_search" class="form-control" placeholder="search for screen title">
	  <span class="input-group-addon"><i class="fa fa-search"></i></span>
	</div>
   {% load slide_tags %}
   <div role="tabpanel" class="tab-pane active" id="my_screens">
   	<div class="row">
   	{% for screen in screens %}
   	{% screen_item screen %}
   	{% if forloop.counter|divisibleby:4 %}<div class="clearfix"></div>{% endif %}
   	{% if mode != 'manage' %}
   	{% endif %}

   	{% endfor %}
   	</div>
   </div>
      <div role="tabpanel" class="tab-pane" id="group_screens">
      <div class="row">
         {% for group in groups %}
            <div class="panel panel-default">
              <div class="panel-heading"><span class="panel-title">{{group.title}} </span> <span class="text-muted">owned by {% if group.owner == user %}me{% else %}{{group.owner.username}}{% endif %}</span></div>
              <div class="panel-body">
                {% for screen in group.screens.all %}
                  {% screen_item screen %}
                  {% endfor %}
              </div>
            </div>

         {% endfor %}
      </div>
   </div>
</div>

<script>
$(function(){
var currentTimeout

 $(document).on('change propertychange keyup', '#my_screens_search', function(){
 	var search = $(this).val().toLowerCase();
 	if (search.length > 3){
 		clearTimeout(currentTimeout);
 		currentTimeout = setTimeout(function(){
 			var thistab = $("#screenpanes div.active")
 			$('.screenItem', thistab).each(function(){
 				console.log($(this).data('title'))
 				console.log(($(this).data('title').indexOf(search)))
 				if ($(this).data('title').toLowerCase().indexOf(search) > -1){
 					console.log(true)
 					$(this).show()
 				}
 				else {
 					$(this).hide()
 				}
 			})
 		}, 350)
 	}
 	else {
 		var thistab = $("#screenpanes div.active")
 		$('.screenItem', thistab).each(function(){
 			$(this).show()
 			})
 	}
 })
})
</script>

templates/screens/screens.html
{% extends 'UI/skin.html' %}
{% load breadcrumbs %}

{% block breadcrumbs %}
{% breadcrumb_url 'Screens' 'screens' %}
{% endblock %}

{% block style %}
<style>
	.tab-content{
		background-color:white;
		border-left:1px solid ddd;
		border-right:1px solid ddd;
		border-bottom:1px solid ddd;
		margin-left: 1px;
	}
	.tab-pane{
		padding:30px;
	}
	.sharebuttoncontainer{
		display: block;
	}
</style>
{% endblock %}

{% block body %}
<div class="container-fluid">
<div class="row">
	<div class="col-lg-6 col-lg-push-6 col-xs-12">
	<h2>Screens <small class="text-muted">Point, click, go.</small></h2>
	<p>Screens are exactly what they sound like -- digital representations of physical screens.</p>
	<p>Each time you set up a physical screen in the real world, you can create a digital screen in Scinage to represent it. This will allow you to point a physical screen to a different slideshow, station, or slide without having to go fiddle with the physical screen at all!</p>
	<a href={% url 'new_screen' %} class="btn btn-primary btn-lg">New Screen</a>

	</div>
	<div id="listScreenLoader" class="col-lg-6 col-lg-pull-6 col-xs-12">
		
	</div>
</div>
</div>
<!-- Modal -->
<div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="shareModalLabel">Share settings for <span id="sharetitle"></span></h4>
      </div>
      <div id="shareModalBody" class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" id="saveshare" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="shareModalLabel">Share Screen<span id="sharetitle"></span></h4>
      </div>
      <div id="shareModalBody" class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" id="saveshare" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="transferModal" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="shareModalLabel">Transfer Screen<span id="sharetitle"></span></h4>
      </div>
      <div id="transferModalBody" class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" id="dotransfer" class="btn btn-primary">Transfer Item</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script>
	$('#listScreenLoader').load('{% url "list_screens" %}')
	$('#listScreenLoader').on('click', '.sharebutton', function(){
		$('#shareModalBody').load('/share/screen/'+$(this).data('itempk')+'/', function(){
			$('#shareModal').modal('show');
		})
	})
	$('#listScreenLoader').on('click', '.transferbutton', function(){
		$('#transferModalBody').load('/transfer/screen/'+$(this).data('itempk')+'/', function(){
			$('#transferModal').modal('show');
		})
	})
</script>
{% endblock %}

templates/screens/viewscreen.html
<html>
<head>
	<style type="text/css">
	body{
		margin:0;
		padding:0;
		background-color: #474d57;
		min-height:100%;
		height: 100%;
		max-height: 100%;
		min-height: 100vh;
		height: 100vh;
		max-height: 100vh;

	}
	</style>
<script src="/static/js/jquery-2.2.0.min.js"></script>
<script>
	$(function(){
		$('body').load('{{screen.link}}')
		var link = "{{screen.link}}"
		setInterval(function(){
			$.get('/screens/ping/{{screen.slug}}/', function(data){
				if (data != link){
					location.reload();
				}
			})
		}, 3000)
	})
</script>
</head>
<body>
</body>
</html>