scinage/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'cas.views.login', name='login'),
    url(r'^accounts/logout/$', 'cas.views.logout', name='logout'),


    url(r'^$', 'layers.views.frontpage', name="home"),
    url(r'^uploadimage/$', 'layers.views.ajaximage', name="upload_image"),
    # Layer Editing
    url(r'^extracontrols/$', 'layers.views.controlsExtra', name="extra_controls"),

    url(r'^layers/search/', include('haystack.urls')),
    url(r'^layers/$', 'layers.views.manageLayers', name="layers"),
    url(r'^layers/list/(?P<mode>\w+)/$', 'layers.views.listLayers', name="list_layers"),
    url(r'^layers/new/$', 'layers.views.editLayer', name="new_layer"),
    url(r'^layers/clone/(?P<layer_id>\d+)/$', 'layers.views.cloneLayer', name="clone_layer"),
    url(r'^layers/edit/(?P<layer_id>\d+)/$', 'layers.views.editLayer', name="edit_layer"),
    url(r'^layers/delete/(?P<layer_id>\d+)/$', 'layers.views.editLayer', name="delete_layer"),
    url(r'^layers/view/(?P<layer_id>\d+)/$', 'layers.views.editLayer', name="view_layer"),
    url(r'^layers/editorinput/(?P<id>\d+)/$', 'layers.views.loadInput'),
    url(r'^layers/favlayer/$', 'layers.views.toggleLayerFav', name='favlayer'),

    # Slide Editing
    url(r'^slides/$', 'layers.views.manageSlides', name="slides"),
    url(r'^slides/list/(?P<mode>\w+)/$', 'layers.views.listSlides', name="list_slides"),
    url(r'^slides/new/$', 'layers.views.editSlide', name="new_slide"),
    url(r'^slides/clone/(?P<slide_id>\d+)/$', 'layers.views.cloneSlide', name="clone_slide"),
    url(r'^slides/edit/(?P<slide_id>\d+)/$', 'layers.views.editSlide', name="edit_slide"),
    url(r'^slides/delete/(?P<slide_id>\d+)/$', 'layers.views.editSlide', name="delete_slide"),
    url(r'^slides/layersettings/(?P<version_id>\d+)/$', 'layers.views.layerSettings'),
    url(r'^slides/layerjson/new/(?P<version_id>\d+)/$', 'layers.views.newLayerJson'),
    url(r'^slides/layerpreview/$', 'layers.views.previewLayer'),

    # Slide Viewing
    url(r'^slides/view/(?P<slide_id>\d+)/$', 'layers.views.viewSlide', name="view_slide"),


    # Slideshow Viewing
    url(r'^slideshows/$', 'layers.views.manageSlideshows', name="slideshows"),
    url(r'^slideshows/list/(?P<mode>\w+)/$', 'layers.views.listSlideshows', name="list_slideshows"),
    url(r'^slideshows/new/$', 'layers.views.editSlideshow', name="new_slideshow"),
    url(r'^slideshows/clone/(?P<slideshow_id>\d+)/$', 'layers.views.cloneSlideshow', name="clone_slideshow"),

    url(r'^slideshows/edit/(?P<slideshow_id>\d+)/$', 'layers.views.editSlideshow', name="edit_slideshow"),
    url(r'^slideshows/delete/(?P<slideshow_id>\d+)/$', 'layers.views.editSlideshow', name="delete_slideshow"),
    url(r'^slideshows/nextslide/(?P<slideshow_id>\d+)/(?P<current_index>\d+)/$', 'layers.views.nextSlide'),
    url(r'^slideshows/view/(?P<slideshow_id>\d+)/$', 'layers.views.viewSlideshow', name="view_slideshow"),

    # Screen Viewing
    url(r'^screens/$', 'layers.views.manageScreens', name="screens"),
    url(r'^screens/list/$', 'layers.views.listScreens', name="list_screens"),
    url(r'^screens/new/$', 'layers.views.editScreen', name="new_screen"),
    url(r'^screens/edit/(?P<screen_id>\d+)/$', 'layers.views.editScreen', name="edit_screen"),
    url(r'^screens/delete/(?P<screen_id>\d+)/$', 'layers.views.editScreen', name="delete_screen"),
    url(r'^screens/view/(?P<slug>[-\w\d]+)/$', 'layers.views.viewScreen', name="view_screen"),
    url(r'^screens/ping/(?P<slug>[-\w\d]+)/$', 'layers.views.pingScreen', name="ping_screen"),


    # Station Stuff
    url(r'^stations/$', 'layers.views.manageStations', name="stations"),

    # Group stuff
    url(r'^groups/$', 'layers.views.manageGroups', name="groups"),
    url(r'^groups/list/(?P<mode>\w+)/$', 'layers.views.listGroups', name="list_groups"),
    url(r'^groups/new/$', 'layers.views.editGroup', name="new_group"),
    url(r'^groups/edit/(?P<group_id>\d+)/$', 'layers.views.editGroup', name="edit_group"),
     url(r'^groups/view/(?P<group_id>\d+)/$', 'layers.views.viewGroup', name="view_group"),
    url(r'^groups/delete/(?P<group_id>\d+)/$', 'layers.views.editGroup', name="delete_group"),

    # Sharing
    url(r'^share/(?P<item>\w+)/(?P<pk>\d+)/$', 'layers.views.shareSettings', name="sharesettings"),
    url(r'^transfer/(?P<item>\w+)/(?P<pk>\d+)/$', 'layers.views.transferOwnership', name="transfer"),

]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static('/media/', document_root=settings.MEDIA_ROOT)

layers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator, ValidationError

from django.db.models.deletion import Collector
from django.db.models.fields.related import ForeignKey

from django.utils.text import slugify

from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFit, ResizeToFill

from taggit.managers import TaggableManager
from haystack import signals

"""
When a user creates a new layer, it will create a version to go with it.
Anytime a user wants to change what their layer looks like, it will create a new
version for the revision, and (if it is not shared) offer to delete older versions.

A version is simply a list of input types and the jinja2(?) html code to render the object

Input types will each contain html / css / js to add an extra field for users to fill in.
We'll have colorpickers and shit.
"""
variable = RegexValidator(r'^[a-zA-Z]{1}[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed. Must start with a letter.')


class UploadedImage(models.Model):
    owner = models.ForeignKey(User)
    creation_date = models.DateTimeField(auto_now_add=True)
    image = ProcessedImageField(upload_to='uploaded_images',
                                processors=[ResizeToFit(1280, 720, False)],
                                format='PNG',
                                options={'quality': 80})
    thumbnail = ImageSpecField(source='image',
                               processors=[ResizeToFit(100, 100)],
                               format='JPEG',
                               options={'quality': 60})


class Layer(models.Model):
    owner = models.ForeignKey(User)
    creation_date = models.DateTimeField(auto_now_add=True)
    shared = models.BooleanField(default=False)
    official = models.BooleanField(default=False)
    title = models.CharField(max_length=255)
    short = models.CharField(max_length=12)
    description = models.TextField()
    tags = TaggableManager()

    # tags
    icon = ProcessedImageField(upload_to='icons',
                               processors=[ResizeToFit(72, 72)],
                               format='PNG',
                               options={'quality': 80},
                               blank=True, null=True)

    def bleeding_edge(self):
        pass

    def latest(self):
        try:
            return self.version_set.filter(publish=True).order_by('-creation_date')[0:1].get()
        except:
            return self.version_set.order_by('-creation_date')[0:1].get()

    def uses(self):
        return SlideLayer.objects.filter(version__layer=self).count()

    def favs(self):
        return self.favoritelayer_set.all().count()

    def clone(self, user):
        newlayer = Layer.objects.get(id=self.id)
        newlayer.id = None
        newlayer.shared = False
        newlayer.official = False
        newlayer.title = "CLONE OF %s" % self.title
        newlayer.owner = user

        newlayer.save()

        # And make the version...
        oldversion = self.latest()
        newversion = self.latest()

        newversion.id = None
        newversion.publish = False
        newversion.changes = ''
        newversion.layer = newlayer
        newversion.save()
        for control in oldversion.control_set.all():
            newcontrol = Control(version=newversion,
                                 title=control.title,
                                 variable_name=control.variable_name,
                                 verbose=control.verbose,
                                 input_type=control.input_type,
                                 default=control.default)
            newcontrol.save()
        return newlayer


class FavoriteLayer(models.Model):
    user = models.ForeignKey(User)
    layer = models.ForeignKey(Layer)


class Version(models.Model):
    layer = models.ForeignKey(Layer)
    content = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)
    changes = models.TextField(blank=True)
    publish = models.BooleanField(default=False)
    # every edit after a publish will be a new version!

    last_edit = models.ForeignKey(User, blank=True, null=True, related_name='version_last_edit')

    def save(self, *args, **kwargs):
        super(Version, self).save(*args, **kwargs)
        if self.publish is True:
            # We're going to do this by hand because stackoverflow only has answers for ancient versions of django
            # and I spent too bloody long trying to write a general duplicator and got only nonsense error messages
            # Duplicate the object to make a new HEAD version.
            new = Version(layer=self.layer, content=self.content, publish=False, last_edit=self.last_edit)
            new.save()
            # Get all the controls too
            for control in self.control_set.all():
                newcontrol = Control(version=new,
                                     title=control.title,
                                     variable_name=control.variable_name,
                                     verbose=control.verbose,
                                     input_type=control.input_type,
                                     default=control.default)
                newcontrol.save()


class InputType(models.Model):
    title = models.CharField(max_length=255)
    html = models.TextField()
    validator = models.CharField(max_length=255)
    validator_error = models.CharField(max_length=255)

    def __unicode__(self):
        return self.title


class Control(models.Model):
    version = models.ForeignKey(Version)
    title = models.CharField(max_length=255)
    variable_name = models.CharField(max_length=18)
    verbose = models.TextField(blank=True)
    input_type = models.ForeignKey(InputType)
    default = models.CharField(max_length=255)


class Slide(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    data = models.TextField(blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    last_edit = models.ForeignKey(User, null=True, related_name='slide_edit_user', blank=True)

    # Advanced Settings
    aspect_ratio = models.CharField(max_length=8, default="16x9",
                                    validators=[RegexValidator(
                                    regex='^(\d+x\d+)$',
                                    message='Must be in the form WidthxHeight',)])

    def clone(self, user):
        # Clone the original...
        newslide = Slide.objects.get(pk=self.id)
        newslide.pk = None
        newslide.owner = user
        newslide.title = 'CLONE OF %s' % self.title
        newslide.save()

        # And get all the slidelayers
        for sl in self.slidelayer_set.all():
            sl.pk = None
            sl.slide = newslide
            sl.save()
        return newslide


class SlideLayer(models.Model):
    slide = models.ForeignKey(Slide)
    x = models.FloatField(default=40)
    y = models.FloatField(default=40)
    width = models.FloatField(default=20)
    height = models.FloatField(default=20)
    title = models.CharField(max_length=100)
    index = models.IntegerField()
    version = models.ForeignKey(Version)
    data = models.TextField(blank=True)

    def control(self):
        return self.version.control


class Slideshow(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    last_edit = models.ForeignKey(User, null=True, related_name='slideshow_last_edit', blank=True)

    def clone(self, user):
        # Clone the original...
        newslideshow = Slideshow.objects.get(pk=self.id)
        newslideshow.pk = None
        newslideshow.owner = user
        newslideshow.title = 'CLONE OF %s' % self.title
        newslideshow.save()

        # And get all the slideshowslides
        for sl in self.slideshowslide_set.all():
            sl.pk = None
            sl.slideshow = newslideshow
            sl.save()
        return newslideshow


class SlideshowSlide(models.Model):
    slideshow = models.ForeignKey(Slideshow)
    slide = models.ForeignKey(Slide)
    length = models.IntegerField(default=30)
    order = models.IntegerField()


class Channel(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    last_edit = models.ForeignKey(User, null=True, related_name='channel_last_edit', blank=True)


class ChannelItem(models.Model):
    channel = models.ForeignKey(Channel)

    # Is it a slide or a slideshow? Form requires one or the other to be true
    slide = models.ForeignKey(Slide, blank=True, null=True)
    slideshow = models.ForeignKey(Slideshow, blank=True, null=True)

    priority = models.IntegerField(default=1)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    repeat = models.CharField(max_length=200)


class Screen(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255, unique=True, help_text="If title changes after initial configuration, URL will change.")
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=255)

    link = models.CharField(max_length=255)
    ip = models.GenericIPAddressField(blank=True, null=True)
    last_connect = models.DateTimeField(blank=True, null=True)

    def save(self, *args, **kwargs):

templates/layers/editlayer.html
{% extends 'UI/skin.html' %}
{% load breadcrumbs %}

{% block breadcrumbs %}
{% breadcrumb_url 'Layers' 'layers' %}
	{% if layer != None %}
	{% with "Edit: "|add:layer.title as current %}
		{% breadcrumb current %}
	{% endwith %}
	{% else %}
    {% breadcrumb 'New Layer' %}
    {% endif %}
{% endblock %}

{% block style %}
	<style>
		body{
			padding: 0;
			margin: 0;
		}
		#layersettings{
			padding-top:55px;
			width: 50%;
			height: 100%;
			overflow-y: scroll;
			position: absolute;
			left: 0;
			top:0;
			background-color: #E6E6E6;
		}
		#preview-holder{
			padding-top:65px;
			padding-left:15px;
			width: 50%;
			height: 100%;
			position: absolute;
			right: 0;
			top:0;
			background-color: #373d47;
		}
		#preview{
			background: #474d57;
			outline: 3px solid white;
			overflow: hidden;
			resize: both;
			width: 160px;
			height: 120px;
			min-width: 10px;
			min-height: 10px;
			max-width: 40vw;
			max-height: 80vh;
		}
		#controls{
			width: 100%;
		}
		.ui-sidebar-wrapper{
			height:100vh;
		}
	</style>
{% endblock %}

{% block body %}
	<div id="layersettings">
	<div class="col-xs-12">
		<br>
		<form id="controls_form" method="POST" action="/layers/preview/" enctype="multipart/form-data">
		{% load crispy_forms_tags %}

		{% crispy layerform %}
		{% crispy versionform %}
		<button type="button" id="preview-button">Preview</button>
		<button type="button" id="submit-button">Submit</button>
		{% crispy controlsform helper %}
		<table id="empty_form" style="display:none">
			<tbody>
                {% crispy controlsform.empty_form trhelper%}
      </tbody>
		</table>
		<button type="button" id="addcontrol">Add Control</button>
		</form>
	</div>
	</div>

	<div id="preview-holder">
		<iframe name="preview_frame" id="preview" width="160px" height="120px" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0">>
		</iframe>
	</div>


 <div id="controls-extra">
 </div>

{% endblock %}
{% block script %}

	<script>

		$(function(){
			var doc = $("#preview")[0].contentWindow.document;
			var body = $('body',doc);
			body.html({{preview|safe}})
			$( "#preview" ).draggable({
			  containment: "parent"
			});

			$("#controls-extra").load('{% url 'extra_controls' %}')
			$('#preview-button').click(function(ev){
				{% if layer != None %}
				$('#controls_form').attr('action', '/layers/edit/{{layer.id}}/?preview=True').attr('target', 'preview_frame').submit()
				{% else %}
				$('#controls_form').attr('action', '/layers/new/?preview=True').attr('target', 'preview_frame').submit();
				{% endif %}
			})
			$('#submit-button').click(function(ev){
				{% if layer != None %}
				$('#controls_form').attr('action', '/layers/edit/{{layer.id}}/').attr('target', '').submit()
				{% else %}
				$('#controls_form').attr('action', '/layers/new/').attr('target', '').submit();
				{% endif %}
			})
			$('#id_publish').click (function(){
			  var thisCheck = $(this);

			  if ( thisCheck.is(':checked') ) {
			  	$("#changesmodal").modal({'show': true})
			    
			  }
			});
			// Change default input html when changing thingies
			$('#controls').on('change', '.type', function(ev){
				var row = $(this).closest('tr')
				row.find('.defaultinput').load('/layers/editorinput/'+$(this).val())
			})

			$('#addcontrol').click(function(ev){
						ev.preventDefault();
						var count = $('#controls_container > tbody > tr').length;
						var tmplMarkup = $('#empty_form>tbody').html();
						var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
						$('table#controls_container>tbody').append(compiledTmpl);

						// update form count
						$('#id_controls-TOTAL_FORMS').attr('value', count+1);
					})

		})
	</script>
{% endblock %}

templates/layers/extra_control_selectors.html
<!-- Modal -->
<div class="modal fade" id="fileModal" tabindex="-1" role="dialog" aria-labelledby="fileModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="fileModalLabel">Select or Upload Image</h4>
      </div>
      <div class="modal-body">
        <div class="input-group">
          <input id="image_select_url" type="text" class="form-control" placeholder="URL Here">
          <span class="input-group-btn">
            <button id="image_select_ok" class="btn btn-success" type="button">OK</button>
          </span>
        </div><!-- /input-group -->
      	<input id="image_upload" type="file" class="form-control">
      	<table class="table">
        	<colgroup>
        	   <col span="1" style="width: 130px;">
        	   <col span="1">
        	</colgroup>
      	<tbody id="image_list">
      		{% for image in images %}
                       {% if image.image %}
      			<tr>
      				<td class="text-center"><img src="{{image.thumbnail.url}}" height="100px"></td><td>
      				<p><small>{{image.creation_date}}</small></p>
      				<p><small class="image_url">https://{{request.get_host}}{{image.image.url}}</small></p>
      				</td>
      			</tr>
                        {% endif %}
      		{% endfor %}
      	</tbody>
      	</table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>


  <script>
  var selected_default;
  $(function(){
    $('#controls_container').on('click', '.textInput[name$="default"]', function(){
      selected_default = $(this);
      var val = $(this).closest('tr').find('.select[name$="input_type"] option:selected').text()
      console.log(val)
      if (val == 'Image'){
        $('#fileModal').modal('show');
      }
    })
    $('#layersettings').on('click', '.image-select-input', function(){
      selected_default = $(this);
      $('#fileModal').modal('show');
    })
    $("#image_upload").on('change' ,function(){
          var image = $('#image_upload')[0].files[0];
          data = new FormData();
          data.append('image', image)
          data.append('csrfmiddlewaretoken', '{{ csrf_token }}')
          //POST SELECTED TO /update/id
          $.ajax({
              url: "/uploadimage/",
              data: data,
              processData: false,
              contentType: false,
              type: 'POST',
              dataType:'json',
              success: function(data){
                var newrow = $("<tr></tr>");
                newrow.append('<td class="text-center"><img src="'+data.thumb+'" height="100px"></td>')
                newrow.append('<td><p><small>Just Now</small></p><p><small class="image_url">http://{{request.get_host}}'+data.image+'</small></p></td>')
                $("#image_list").prepend(newrow);
                newrow.click()
            }
          })
          $(this).parent().siblings('.displayImage').removeAttr('style')
          $(function( data ){
            console.log(data);
          })
          var item = $(this).attr('name')
          var icon = $("#" + item + "image")
          icon.css({"display":"inline"})
        })
    $("#image_list").on('click', 'tr', function(){
      $('#image_select_url').val($(this).find('.image_url').text());
      $('#image_select_ok').click();
    })
    $("#image_select_ok").click(function(){
      selected_default.val($('#image_select_url').val());
      selected_default.change();
      $('#fileModal').modal('hide');
    })
  })
  </script>

templates/layers/layer_list.html
<ul id="layertabs" class="nav nav-tabs" role="tablist" style="margin-top:10px;">
        <li role="presentation" class="active"><a href="#fav_layers" aria-controls="fav_layers" role="tab" data-toggle="tab">Favorite Layers</a></li>
        <li role="presentation"><a href="#pub_layers" aria-controls="pub_layers" role="tab" data-toggle="tab">Public Layers</a></li>
		  <li role="presentation"><a href="#my_layers" aria-controls="my_layers" role="tab" data-toggle="tab">My Layers</a></li>
		  <li role="presentation"><a href="#group_layers" aria-controls="group_layers" role="tab" data-toggle="tab">Layers in Groups</a></li>
</ul>
<div id="layerpanes" class="tab-content" style="">
	<div class="input-group" style="padding:20px;">
	  <input type="text" id="my_layers_search" class="form-control" placeholder="search for layer title">
	  <span class="input-group-addon"><i class="fa fa-search"></i></span>
	</div>
   {% load slide_tags %}
   <div role="tabpanel" class="tab-pane active" id="fav_layers">
      <div class="row">
      <h4 style="margin-top:0;">
         Recently Used
      </h4>
      <div class="col-xs-12">
      {% for layer in recent %}
         {% if mode != "edit" %}
           {% layer_item_fav layer 'use' %}
         {% else %}
           {% layer_item_fav layer mode %}
         {% endif %}
      {% endfor %}
      </div>
      <hr>
      <br>
      <h4 style="margin-top:0;">
         Favorites
      </h4>
      <div class="col-xs-12">
      {% for layer in favorites %}
         {% if mode != "edit" %}
           {% layer_item_fav layer 'use' %}
         {% else %}
           {% layer_item_fav layer mode %}
         {% endif %}
         {% if forloop.counter|divisibleby:4 %}<div class="clearfix"></div>{% endif %}
      {% endfor %}
      </div>
      </div>


   </div>
   <div role="tabpanel" class="tab-pane" id="pub_layers">
      <h3 style="margin-top: 0;"><small>Search the Public Layer Database above</small></h3>
      <div id="layersearch" class="row">
      <h3>Popular Layers</h3>
      {% for layer in popular %}
         {% layer_item_fav layer 'store' %}
      {% endfor %}
      </div>
   </div>
   <div role="tabpanel" class="tab-pane" id="my_layers">
   	<div class="row">
   	{% for layer in layers %}
   	{% layer_item_fav layer mode %}
   	{% if forloop.counter|divisibleby:4 %}<div class="clearfix"></div>{% endif %}
   	{% if mode != 'manage' %}
   	{% endif %}

   	{% endfor %}
   	</div>
   </div>
   <div role="tabpanel" class="tab-pane" id="group_layers">
      {% for group in groups %}
         <div class="panel panel-default">
           <div class="panel-heading"><span class="panel-title">{{group.title}} </span> <span class="text-muted">owned by {% if group.owner == user %}me{% else %}{{group.owner.username}}{% endif %}</span></div>
           <div class="panel-body">
             {% for layer in group.layers.all %}
               {% layer_item_fav layer mode %}
               {% if forloop.counter|divisibleby:4 %}<div class="clearfix"></div>{% endif %}
               {% endfor %}
           </div>
         </div>

      {% endfor %}
   </div>
</div>

<script>
$(function(){
var currentTimeout

 $(document).on('change propertychange keyup', '#my_layers_search', function(e){
 	var search = $(this).val().toLowerCase();
   var thistab = $("#layerpanes div.active")
    if (thistab.attr('id') == "pub_layers"){
      if(e.keyCode == 13){
         $('#layersearch').load('/layers/search/?q='+search)
      }
   }
   else{
    	if (search.length > 3){
    		clearTimeout(currentTimeout);
    		currentTimeout = setTimeout(function(){
           
    			$('.layerItem', thistab).each(function(){
    				console.log($(this).data('title'))
    				console.log(($(this).data('title').indexOf(search)))
    				if ($(this).data('title').toLowerCase().indexOf(search) > -1){
    					console.log(true)
    					$(this).show()
    				}
    				else {
    					$(this).hide()
    				}
    			})
    		}, 350)
    	}
    	else {
    		var thistab = $("#layerpanes div.active")
    		$('.layerItem', thistab).each(function(){
    			$(this).show()
    			})
    	}
   }
 })
 $("#layerpanes").on('click', '.favtoggle', function(){
   var container = $(this).closest('.layerItem');
   var itemid = container.data('id')
   $.post('{% url 'favlayer' %}', {'id': itemid, 'csrfmiddlewaretoken': '{{csrf_token}}'}, function(data){
      var affected_layers = $('#layerpanes').find('.layerItem[data-id="'+itemid+'"]>div>div>span>.favtoggle')
      console.log(affected_layers)
      if(data == "ADDED"){
         affected_layers.removeClass('fa-star-o');
         affected_layers.addClass('fa-star');
      }
      else{
         affected_layers.removeClass('fa-star');
         affected_layers.addClass('fa-star-o');
      }

   })
 })
  $("#layerpanes").on('click', '.previewtoggle', function(){
   var icon = $(this);
   var container = $(this).closest('.layerItem');
   var itemid = container.data('version');
   if (icon.hasClass('fa-eye')){
      $.post('/slides/layerpreview/', {'version': itemid}, function(data){
         var iframe = $('<iframe width="100%" height="200px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0"></iframe>').attr('srcdoc', data)

         container.find('.layerpreview>div').html(iframe)
         container.find('.layerpreview').slideDown();

      })
   }
   else{
      container.find('.layerpreview').hide()
      container.find('.layerpreview iframe').remove()
   }
   icon.toggleClass('fa-eye fa-eye-slash')
  })
})
</script>