scinage/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'cas.views.login', name='login'),
    url(r'^accounts/logout/$', 'cas.views.logout', name='logout'),


    url(r'^$', 'layers.views.frontpage', name="home"),
    url(r'^uploadimage/$', 'layers.views.ajaximage', name="upload_image"),
    # Layer Editing
    url(r'^extracontrols/$', 'layers.views.controlsExtra', name="extra_controls"),

    url(r'^layers/search/', include('haystack.urls')),
    url(r'^layers/$', 'layers.views.manageLayers', name="layers"),
    url(r'^layers/list/(?P<mode>\w+)/$', 'layers.views.listLayers', name="list_layers"),
    url(r'^layers/new/$', 'layers.views.editLayer', name="new_layer"),
    url(r'^layers/clone/(?P<layer_id>\d+)/$', 'layers.views.cloneLayer', name="clone_layer"),
    url(r'^layers/edit/(?P<layer_id>\d+)/$', 'layers.views.editLayer', name="edit_layer"),
    url(r'^layers/delete/(?P<layer_id>\d+)/$', 'layers.views.editLayer', name="delete_layer"),
    url(r'^layers/view/(?P<layer_id>\d+)/$', 'layers.views.editLayer', name="view_layer"),
    url(r'^layers/editorinput/(?P<id>\d+)/$', 'layers.views.loadInput'),
    url(r'^layers/favlayer/$', 'layers.views.toggleLayerFav', name='favlayer'),

    # Slide Editing
    url(r'^slides/$', 'layers.views.manageSlides', name="slides"),
    url(r'^slides/list/(?P<mode>\w+)/$', 'layers.views.listSlides', name="list_slides"),
    url(r'^slides/new/$', 'layers.views.editSlide', name="new_slide"),
    url(r'^slides/clone/(?P<slide_id>\d+)/$', 'layers.views.cloneSlide', name="clone_slide"),
    url(r'^slides/edit/(?P<slide_id>\d+)/$', 'layers.views.editSlide', name="edit_slide"),
    url(r'^slides/delete/(?P<slide_id>\d+)/$', 'layers.views.editSlide', name="delete_slide"),
    url(r'^slides/layersettings/(?P<version_id>\d+)/$', 'layers.views.layerSettings'),
    url(r'^slides/layerjson/new/(?P<version_id>\d+)/$', 'layers.views.newLayerJson'),
    url(r'^slides/layerpreview/$', 'layers.views.previewLayer'),

    # Slide Viewing
    url(r'^slides/view/(?P<slide_id>\d+)/$', 'layers.views.viewSlide', name="view_slide"),


    # Slideshow Viewing
    url(r'^slideshows/$', 'layers.views.manageSlideshows', name="slideshows"),
    url(r'^slideshows/list/(?P<mode>\w+)/$', 'layers.views.listSlideshows', name="list_slideshows"),
    url(r'^slideshows/new/$', 'layers.views.editSlideshow', name="new_slideshow"),
    url(r'^slideshows/clone/(?P<slideshow_id>\d+)/$', 'layers.views.cloneSlideshow', name="clone_slideshow"),

    url(r'^slideshows/edit/(?P<slideshow_id>\d+)/$', 'layers.views.editSlideshow', name="edit_slideshow"),
    url(r'^slideshows/delete/(?P<slideshow_id>\d+)/$', 'layers.views.editSlideshow', name="delete_slideshow"),
    url(r'^slideshows/nextslide/(?P<slideshow_id>\d+)/(?P<current_index>\d+)/$', 'layers.views.nextSlide'),
    url(r'^slideshows/view/(?P<slideshow_id>\d+)/$', 'layers.views.viewSlideshow', name="view_slideshow"),

    # Screen Viewing
    url(r'^screens/$', 'layers.views.manageScreens', name="screens"),
    url(r'^screens/list/$', 'layers.views.listScreens', name="list_screens"),
    url(r'^screens/new/$', 'layers.views.editScreen', name="new_screen"),
    url(r'^screens/edit/(?P<screen_id>\d+)/$', 'layers.views.editScreen', name="edit_screen"),
    url(r'^screens/delete/(?P<screen_id>\d+)/$', 'layers.views.editScreen', name="delete_screen"),
    url(r'^screens/view/(?P<slug>[-\w\d]+)/$', 'layers.views.viewScreen', name="view_screen"),
    url(r'^screens/ping/(?P<slug>[-\w\d]+)/$', 'layers.views.pingScreen', name="ping_screen"),


    # Station Stuff
    url(r'^stations/$', 'layers.views.manageStations', name="stations"),

    # Group stuff
    url(r'^groups/$', 'layers.views.manageGroups', name="groups"),
    url(r'^groups/list/(?P<mode>\w+)/$', 'layers.views.listGroups', name="list_groups"),
    url(r'^groups/new/$', 'layers.views.editGroup', name="new_group"),
    url(r'^groups/edit/(?P<group_id>\d+)/$', 'layers.views.editGroup', name="edit_group"),
     url(r'^groups/view/(?P<group_id>\d+)/$', 'layers.views.viewGroup', name="view_group"),
    url(r'^groups/delete/(?P<group_id>\d+)/$', 'layers.views.editGroup', name="delete_group"),

    # Sharing
    url(r'^share/(?P<item>\w+)/(?P<pk>\d+)/$', 'layers.views.shareSettings', name="sharesettings"),
    url(r'^transfer/(?P<item>\w+)/(?P<pk>\d+)/$', 'layers.views.transferOwnership', name="transfer"),

]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static('/media/', document_root=settings.MEDIA_ROOT)

layers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator, ValidationError

from django.db.models.deletion import Collector
from django.db.models.fields.related import ForeignKey

from django.utils.text import slugify

from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFit, ResizeToFill

from taggit.managers import TaggableManager
from haystack import signals

"""
When a user creates a new layer, it will create a version to go with it.
Anytime a user wants to change what their layer looks like, it will create a new
version for the revision, and (if it is not shared) offer to delete older versions.

A version is simply a list of input types and the jinja2(?) html code to render the object

Input types will each contain html / css / js to add an extra field for users to fill in.
We'll have colorpickers and shit.
"""
variable = RegexValidator(r'^[a-zA-Z]{1}[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed. Must start with a letter.')


class UploadedImage(models.Model):
    owner = models.ForeignKey(User)
    creation_date = models.DateTimeField(auto_now_add=True)
    image = ProcessedImageField(upload_to='uploaded_images',
                                processors=[ResizeToFit(1280, 720, False)],
                                format='PNG',
                                options={'quality': 80})
    thumbnail = ImageSpecField(source='image',
                               processors=[ResizeToFit(100, 100)],
                               format='JPEG',
                               options={'quality': 60})


class Layer(models.Model):
    owner = models.ForeignKey(User)
    creation_date = models.DateTimeField(auto_now_add=True)
    shared = models.BooleanField(default=False)
    official = models.BooleanField(default=False)
    title = models.CharField(max_length=255)
    short = models.CharField(max_length=12)
    description = models.TextField()
    tags = TaggableManager()

    # tags
    icon = ProcessedImageField(upload_to='icons',
                               processors=[ResizeToFit(72, 72)],
                               format='PNG',
                               options={'quality': 80},
                               blank=True, null=True)

    def bleeding_edge(self):
        pass

    def latest(self):
        try:
            return self.version_set.filter(publish=True).order_by('-creation_date')[0:1].get()
        except:
            return self.version_set.order_by('-creation_date')[0:1].get()

    def uses(self):
        return SlideLayer.objects.filter(version__layer=self).count()

    def favs(self):
        return self.favoritelayer_set.all().count()

    def clone(self, user):
        newlayer = Layer.objects.get(id=self.id)
        newlayer.id = None
        newlayer.shared = False
        newlayer.official = False
        newlayer.title = "CLONE OF %s" % self.title
        newlayer.owner = user

        newlayer.save()

        # And make the version...
        oldversion = self.latest()
        newversion = self.latest()

        newversion.id = None
        newversion.publish = False
        newversion.changes = ''
        newversion.layer = newlayer
        newversion.save()
        for control in oldversion.control_set.all():
            newcontrol = Control(version=newversion,
                                 title=control.title,
                                 variable_name=control.variable_name,
                                 verbose=control.verbose,
                                 input_type=control.input_type,
                                 default=control.default)
            newcontrol.save()
        return newlayer


class FavoriteLayer(models.Model):
    user = models.ForeignKey(User)
    layer = models.ForeignKey(Layer)


class Version(models.Model):
    layer = models.ForeignKey(Layer)
    content = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)
    changes = models.TextField(blank=True)
    publish = models.BooleanField(default=False)
    # every edit after a publish will be a new version!

    last_edit = models.ForeignKey(User, blank=True, null=True, related_name='version_last_edit')

    def save(self, *args, **kwargs):
        super(Version, self).save(*args, **kwargs)
        if self.publish is True:
            # We're going to do this by hand because stackoverflow only has answers for ancient versions of django
            # and I spent too bloody long trying to write a general duplicator and got only nonsense error messages
            # Duplicate the object to make a new HEAD version.
            new = Version(layer=self.layer, content=self.content, publish=False, last_edit=self.last_edit)
            new.save()
            # Get all the controls too
            for control in self.control_set.all():
                newcontrol = Control(version=new,
                                     title=control.title,
                                     variable_name=control.variable_name,
                                     verbose=control.verbose,
                                     input_type=control.input_type,
                                     default=control.default)
                newcontrol.save()


class InputType(models.Model):
    title = models.CharField(max_length=255)
    html = models.TextField()
    validator = models.CharField(max_length=255)
    validator_error = models.CharField(max_length=255)

    def __unicode__(self):
        return self.title


class Control(models.Model):
    version = models.ForeignKey(Version)
    title = models.CharField(max_length=255)
    variable_name = models.CharField(max_length=18)
    verbose = models.TextField(blank=True)
    input_type = models.ForeignKey(InputType)
    default = models.CharField(max_length=255)


class Slide(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    data = models.TextField(blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    last_edit = models.ForeignKey(User, null=True, related_name='slide_edit_user', blank=True)

    # Advanced Settings
    aspect_ratio = models.CharField(max_length=8, default="16x9",
                                    validators=[RegexValidator(
                                    regex='^(\d+x\d+)$',
                                    message='Must be in the form WidthxHeight',)])

    def clone(self, user):
        # Clone the original...
        newslide = Slide.objects.get(pk=self.id)
        newslide.pk = None
        newslide.owner = user
        newslide.title = 'CLONE OF %s' % self.title
        newslide.save()

        # And get all the slidelayers
        for sl in self.slidelayer_set.all():
            sl.pk = None
            sl.slide = newslide
            sl.save()
        return newslide


class SlideLayer(models.Model):
    slide = models.ForeignKey(Slide)
    x = models.FloatField(default=40)
    y = models.FloatField(default=40)
    width = models.FloatField(default=20)
    height = models.FloatField(default=20)
    title = models.CharField(max_length=100)
    index = models.IntegerField()
    version = models.ForeignKey(Version)
    data = models.TextField(blank=True)

    def control(self):
        return self.version.control


class Slideshow(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    last_edit = models.ForeignKey(User, null=True, related_name='slideshow_last_edit', blank=True)

    def clone(self, user):
        # Clone the original...
        newslideshow = Slideshow.objects.get(pk=self.id)
        newslideshow.pk = None
        newslideshow.owner = user
        newslideshow.title = 'CLONE OF %s' % self.title
        newslideshow.save()

        # And get all the slideshowslides
        for sl in self.slideshowslide_set.all():
            sl.pk = None
            sl.slideshow = newslideshow
            sl.save()
        return newslideshow


class SlideshowSlide(models.Model):
    slideshow = models.ForeignKey(Slideshow)
    slide = models.ForeignKey(Slide)
    length = models.IntegerField(default=30)
    order = models.IntegerField()


class Channel(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    last_edit = models.ForeignKey(User, null=True, related_name='channel_last_edit', blank=True)


class ChannelItem(models.Model):
    channel = models.ForeignKey(Channel)

    # Is it a slide or a slideshow? Form requires one or the other to be true
    slide = models.ForeignKey(Slide, blank=True, null=True)
    slideshow = models.ForeignKey(Slideshow, blank=True, null=True)

    priority = models.IntegerField(default=1)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    repeat = models.CharField(max_length=200)


class Screen(models.Model):
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=255, unique=True, help_text="If title changes after initial configuration, URL will change.")
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=255)

    link = models.CharField(max_length=255)
    ip = models.GenericIPAddressField(blank=True, null=True)
    last_connect = models.DateTimeField(blank=True, null=True)

    def save(self, *args, **kwargs):

templates/slideshows/editslideshow.html
{% extends 'UI/skin.html' %}
{% load breadcrumbs %}

{% block breadcrumbs %}
{% breadcrumb_url 'Slideshows' 'layers' %}
	{% if slideshow != None %}
	{% with "Edit: "|add:slideshow.title as current %}
		{% breadcrumb current %}
	{% endwith %}
	{% else %}
    {% breadcrumb 'New Slideshow' %}
    {% endif %}
{% endblock %}

{% block style %}

	<style>
		body{
			padding: 0;
			margin: 0;
			background-color: #E6E6E6;
		}

		.ui-sidebar-wrapper{
			height:100%;
		}

		.slideIcon{
			padding: 8px;
			display: none;
		}
		.activeIcon{
			display: block;
		}

		.slideIcon>.slideContent{
			border: 1px solid black;
			border-radius: 5px;
			padding:8px;
			background-color: #E6E6E6;

		}

		.addbuttoncontainer{
		  display: block;
		}
	</style>
{% endblock %}

{% block body %}
{% load crispy_forms_tags %}
<form action="" method="POST">
<div class="container-fluid" style="padding:20px">
	<div class="row">
		<div class="col-lg-6 col-xs-12">
			{% crispy form %}
		</div>
	</div>
	<div class="btn-group">
		<button type="button" class="btn btn-primary" id="addslide">Add Slide</button>
		<button type="submit" class="btn btn-success">Save Slideshow</button>
	</div>
	{% load slide_tags %}
	{% slideshowslides_all %}
</div>

</form>

<div id="slidesModal" class="modal fade" style="z-index:2000;">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div id="listSlidesLoader" class="modal-body">
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



{% endblock %}
{% block script %}
	<script>
	$('#slidelist>.activeIcon').each(function(){
		if ($(".slideForm>[id$='-DELETE']", this).is(':checked')){
			$(this).removeClass('activeIcon');
		}
	})
	$('#listSlidesLoader').load('{% url "list_slides" mode="edit" %}', function(){
		// Put the pretty stuff in each icon
		$('#slidelist>.activeIcon').each(function(){
			// Get the matching slide
			var icon = $(this)
			var id = $('.slideForm>.slide', icon).val()
			var search = $('.slideItem').filter(function(){return $(this).data("id") == id })
			if (search.length > 0){
				icon.find('.slideContent').prepend(search.find('.info').html())
			}
		})
	})


	function reorder(){
		$('#slidelist>.activeIcon').each(function(index){
			$(".slideForm>.order", this).val(index);
		})
	}

	$('#slidelist').each(function(){
				    var $this = $(this);
				    $this.append($this.find('.activeIcon').get().sort(function(a, b) {
				        return $('.slideForm>.order', a).val() - $('.slideForm>.order', b).val();
				    }));
				});
	

	$( "#slidelist" ).sortable({
		revert: true,
		update: function( event, ui ) {
			reorder();
		}
	});

	$('#addslide').click(function(evt){
		evt.preventDefault();
		$('#slidesModal').modal('show');
	})

	$(document).on('click', '.slidedelete', function(evt){
		evt.preventDefault();
		var slide = $(this).closest('.slideIcon')
		$(".slideForm>[id$='-DELETE']", slide).prop('checked', true);
		slide.removeClass('activeIcon', function(){
			reorder()
		});
	})


	$('#listSlidesLoader').on('click', '.slideItem .addslidebutton', function(evt){
		evt.preventDefault();
		var slideItem = $(this).closest('.slideItem');
			// Get highest layer
			var index_highest = 0;
			$("#slidelist>.activeIcon").each(function() {
			    var index_current = parseInt($(".slideForm>.order",this).val());
			    if(index_current > index_highest) {
			        index_highest = index_current;
			        console.log(index_highest)
			    }
			});
			var count = $('#slidelist>.slideIcon').length;
			var owner = slideItem.find('.owner').text()
			var title = slideItem.find('h4>b').text()
			var tmplMarkup = $('#emptyslide').html();
			var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count).replace(/__title__/g, title).replace(/__owner__/g, owner);
			$('#slidelist').append(compiledTmpl);
			//Grab this newest slide we just added...
			var newlayer = $('#slidelist .slideIcon:last-child')
			// Fill it with goodies from the jsonData
			$(".slideForm>.order", newlayer).val(index_highest+1)
			$(".slideForm>.slide", newlayer).val(slideItem.data('id'))
			$('.slideContent', newlayer).prepend(slideItem.find('.info').html())
			// update form count
			$('#id_slide-TOTAL_FORMS').attr('value', count+1);
			$('#slidesModal').modal('hide');
			reorder();

	})
	</script>
{% endblock %}

templates/slideshows/slideshow_list.html
<ul id="slideshowtabs" class="nav nav-tabs" role="tablist" style="margin-top:10px;">
		  <li role="presentation" class="active"><a href="#my_slideshows" aria-controls="my_slideshows" role="tab" data-toggle="tab">My slideshows</a></li>
		  <li role="presentation"><a href="#group_slideshows" aria-controls="group_slideshows" role="tab" data-toggle="tab">Slideshows in Groups</a></li>
</ul>
<div id="slideshowpanes" class="tab-content" style="">
	<div class="input-group" style="padding:20px;">
	  <input type="text" id="my_slideshows_search" class="form-control" placeholder="search for slideshow title">
	  <span class="input-group-addon"><i class="fa fa-search"></i></span>
	</div>
   {% load slide_tags %}
   <div role="tabpanel" class="tab-pane active" id="my_slideshows">
   	<div class="row">
   	{% for slideshow in slideshows %}
   	{% slideshow_item slideshow %}
   	{% if forloop.counter|divisibleby:4 %}<div class="clearfix"></div>{% endif %}
   	{% if mode != 'manage' %}
   	{% endif %}

   	{% endfor %}
   	</div>
   </div>
      <div role="tabpanel" class="tab-pane" id="group_slideshows">
      <div class="row">
         {% for group in groups %}
            <div class="panel panel-default">
              <div class="panel-heading"><span class="panel-title">{{group.title}} </span> <span class="text-muted">owned by {% if group.owner == user %}me{% else %}{{group.owner.username}}{% endif %}</span></div>
              <div class="panel-body">
                {% for slideshow in group.slideshows.all %}
                  {% slideshow_item slideshow %}
                  {% endfor %}
              </div>
            </div>

         {% endfor %}
      </div>
   </div>
</div>

<script>
$(function(){
var currentTimeout

 $(document).on('change propertychange keyup', '#my_slideshows_search', function(){
 	var search = $(this).val().toLowerCase();
 	if (search.length > 3){
 		clearTimeout(currentTimeout);
 		currentTimeout = setTimeout(function(){
 			var thistab = $("#slideshowpanes div.active")
 			$('.slideshowItem', thistab).each(function(){
 				console.log($(this).data('title'))
 				console.log(($(this).data('title').indexOf(search)))
 				if ($(this).data('title').toLowerCase().indexOf(search) > -1){
 					console.log(true)
 					$(this).show()
 				}
 				else {
 					$(this).hide()
 				}
 			})
 		}, 350)
 	}
 	else {
 		var thistab = $("#slideshowpanes div.active")
 		$('.slideshowItem', thistab).each(function(){
 			$(this).show()
 			})
 	}
 })
})
</script>

templates/slideshows/slideshow_list_single.html
<div data-id="{{slideshow.id}}" data-title="{{slideshow.title}}" data-version="{{slideshow.latest.id}}" class="slideshowItem col-xs-{% if mode == 'manage'%}12{% else %}3{% endif %}">
	<div class="col-xs-{% if mode == 'manage'%}6{% else %}12{% endif %}">
	<h4>{{slideshow.title}}</h4>
	<p>{{slideshow.description}}</p>
	</div>
	{% if mode == 'manage'%}
	<div class="col-xs-6 text-right">
	Owned by: {% if slideshow.owner = user %} Me {% else %} {{slideshow.owner.username}}{% endif %}
	<br>
	Last Edited: {{slideshow.edit_date}}
	<br>
	{% if perms.share == True %}<button class="sharebutton btn btn-default btn-sm" data-itempk="{{slideshow.id}}">Share</button>{% endif %}
	{% if perms.edit == True %}<a href="{% url 'edit_slideshow' slideshow.id %}" class="btn btn-default btn-sm">Edit</a>{% endif %} 
	{% if perms.delete == True %}<a href="{% url 'delete_slideshow' slideshow.id %}" class="btn btn-default btn-sm">Delete</a>{% endif %} 
	<a target="_blank" href="{% url 'view_slideshow' slideshow.id %}" class="btn btn-default btn-sm">View</a>
	</div>
	{% else %}
	<div class="col-xs-12">
		{% if perms.use == True %}
		<button type="button" class=" btn btn-block btn-primary addslideshowbutton">Add</button>
		{% else %}
		<button type="button" class=" btn btn-block btn-primary disabled">Cannot add this item</button>
		{% endif %}
	</div>
	{% endif %}
</div>

templates/slideshows/slideshow_list_single_new.html
<div data-id="{{slideshow.id}}" data-title="{{slideshow.title}}" class="slideshowItem {% if mode == "use" or mode == "edit"%}col-xs-6 col-sm-4 col-md-3{% else %}col-xs-12{% endif %}">
	<div class="itemContainer itemContainerSlideshow row">
	<div class="col-xs-12">
		<span class=""><i class="fa fa-th-list"></i></span>
		<span class="pull-right">
		{% if mode == "manage" %}
		<a target="_blank" href="{% url 'clone_slideshow' slideshow.id %}"><i class="favtoggle fa fa-copy" title="Clone this slideshow"></i></a>
		{% endif %}
		</span>
	</div>
	<div class="col-xs-8">
	<div class="col-xs-12{% if mode == "manage"%}{% else %}text-center{% endif %}">
		<h4 style="margin:0; margin-top:5px"><b>{{slideshow.title}}</b>
		<br>
		<small>(by: {% if slideshow.owner = user %}Me{% else %} {{slideshow.owner.username}}{% endif %})
		<br>
		Last Edited: {{slideshow.edit_date|date:"Y/m/d"}}
		</small>

		</h4>

	</div>
	{% if mode == "manage" %}
		<div class="col-xs-12 itemDescription" style="min-height:100%; margin-top:10px;">
			<p><small></small></p>
			<p>{{slideshow.description}}</p>
		</div>
	</div>
		<div class="col-xs-4">
			<div class="btn-group-vertical btn-block" role="group" aria-label="...">
				{% if perms.share == True %}<button class="sharebutton btn btn-primary btn-sm" data-itempk="{{slideshow.id}}">Share</button>{% endif %}
				{% if perms.edit == True %}<a href="{% url 'edit_slideshow' slideshow.id %}" class="btn btn-primary btn-sm">Edit</a>{% endif %} 
				{% if slideshow.owner == user %}
				<button class="transferbutton btn btn-primary btn-sm" data-itempk="{{slideshow.id}}">Transfer</button>
				{% endif %}
				{% if perms.delete == True %}<a href="{% url 'delete_slideshow' slideshow.id %}" class="btn btn-primary btn-sm">Delete</a>{% endif %} 

				<a href="{% url 'view_slideshow' slideshow.id %}" class="btn btn-primary btn-sm">View</a>
			</div>
		</div>
	{% else %}
	</div>
	{% endif %}
	<div class="col-xs-12 addbuttoncontainer">
		{% if perms.use == True %}
		<button type="button" class=" btn btn-block btn-primary addslideshowbutton">Add</button>
		{% else %}
		<button type="button" class=" btn btn-block btn-primary disabled">Cannot add this item</button>
		{% endif %}
	</div>
	</div>
</div>

templates/slideshows/slideshowrender.html
<html>
<head>
	<style type="text/css">
	body{
		margin:0;
		padding:0;
		background-color: #474d57;
		min-height:100%;
		height: 100%;
		max-height: 100%;
		min-height: 100vh;
		height: 100vh;
		max-height: 100vh;

	}
	.element{
		width: 100vw; height: 100vh; position:fixed; left: 0; top: 0;
	}
	.fade{
		opacity: 1;
		-webkit-transition: opacity 0.6s ease-in-out;
	    -moz-transition: opacity 0.6s ease-in-out;
	    -ms-transition: opacity 0.6s ease-in-out;
	    -o-transition: opacity 0.6s ease-in-out;
	}
	</style>
</head>
<body>

<div id="bg" class="element fade" style="z-index:5; background-color: #000000;"></div>


<iframe src="about:blank" class="element current" style=" z-index:4;"
scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0" sandbox="allow-scripts allow-same-origin">
</iframe>

<div id="bg" class="element" style="z-index:2; background-color: #474d57;"></div>

<iframe src="about:blank" class="element next" style="z-index:1;"
scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0" sandbox="allow-scripts allow-same-origin">
</iframe>


<script src="/static/js/jquery-2.2.0.min.js"></script>

<script>
function nextframe(source, time, index){
	$('.next').attr('src', source)
	$('.next').load()
	$('#bg').css('opacity', 1);
	setTimeout(function(){
		var current = $('.current');
		$('.next').css('z-index', 4);
		$('.next').toggleClass('next current')
		current.attr('src', 'about:blank').load().css('z-index', 1).toggleClass('next current');
		$.get('/slideshows/nextslide/{{slideshow.id}}/'+String(index)+'/', function(data){
			$('#bg').css('opacity', 0);
			console.log([data.slide, data.time, data.index])
			setTimeout(function(){
				setTimeout(function(){nextframe(data.slide, data.time, data.index)}, time)
			}, 600);
		})
	}, 600)
}
$(function(){
	nextframe('{{fs_src}}', {{fs_time}}, 0)
})
</script>
</body>
</html>